version: 2

sources:
  - name: bronze
    database: "{{ env_var('ICEBERG_CATALOG_NAME', 'banking') }}"
    schema: bronze
    tables:
      - name: customers
        columns:
          - name: _id
            tests: [not_null]
      - name: accounts
        columns:
          - name: _id
            tests: [not_null]
      - name: transactions
        columns:
          - name: _id
            tests: [not_null]
      - name: branches
      - name: loans
      - name: cards
      - name: card_transactions
      - name: loan_payments
      - name: support_tickets
      - name: employees
