-- ============================================================
-- StreamFlix Lakehouse - Unity Catalog Initialization
-- Catalog: streamflix-lakehouse
-- Author: Generated by Genie Code
-- Date: 2026-09-14
-- ============================================================
-- Purpose: Initialize medallion architecture (Bronze/Silver/Gold)
--          in Unity Catalog with audit, lineage, and quality tables
-- Usage: Run in Databricks SQL Editor or via CLI:
--        databricks sql execute --file sql/init_schema.sql
-- ============================================================

-- ============================================================
-- 1. Verify Catalog Exists
-- ============================================================
DESCRIBE CATALOG `streamflix-lakehouse`;

-- ============================================================
-- 2. Create Medallion Schemas
-- ============================================================
CREATE SCHEMA IF NOT EXISTS `streamflix-lakehouse`.bronze
  COMMENT 'Bronze layer — raw data ingestion with Auto Loader, schema evolution enabled';

CREATE SCHEMA IF NOT EXISTS `streamflix-lakehouse`.silver
  COMMENT 'Silver layer — cleaned, validated, deduped data with SCD Type 2 and quarantine';

CREATE SCHEMA IF NOT EXISTS `streamflix-lakehouse`.gold
  COMMENT 'Gold layer — business-ready aggregates (DAU/WAU, churn metrics, MRR/ARR)';

CREATE SCHEMA IF NOT EXISTS `streamflix-lakehouse`.init_schema
  COMMENT 'Initialization schema — audit logs, lineage tracking, and scaffolding tables';

-- ============================================================
-- 3. Create Audit & Lineage Tables
-- ============================================================

-- Audit log for quality gate tracking
CREATE TABLE IF NOT EXISTS `streamflix-lakehouse`.silver.audit_log (
  layer STRING COMMENT 'Medallion layer: bronze, silver, or gold',
  table_name STRING COMMENT 'Fully qualified table name',
  pass_count BIGINT COMMENT 'Number of records passing quality checks',
  fail_count BIGINT COMMENT 'Number of records failing quality checks',
  run_at TIMESTAMP COMMENT 'Timestamp of the quality check execution'
) USING DELTA
  COMMENT 'Quality gate audit log — tracks pass/fail counts per pipeline run'
  TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
  );

-- Lineage tracking table
CREATE TABLE IF NOT EXISTS `streamflix-lakehouse`.init_schema.lineage (
  source_table STRING COMMENT 'Upstream source table name',
  target_table STRING COMMENT 'Downstream target table name',
  transform STRING COMMENT 'Transformation description or notebook path',
  updated_at TIMESTAMP COMMENT 'Last update timestamp'
) USING DELTA
  COMMENT 'Data lineage tracker for medallion architecture dependencies'
  TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true'
  );

-- Quarantine table for rejected records
CREATE TABLE IF NOT EXISTS `streamflix-lakehouse`.silver.quarantine (
  source_table STRING COMMENT 'Origin table of the rejected record',
  record_id STRING COMMENT 'Unique identifier of the rejected record',
  record_data STRING COMMENT 'JSON representation of the failed record',
  failure_reason STRING COMMENT 'Quality check failure description',
  quarantined_at TIMESTAMP COMMENT 'Timestamp when record was quarantined'
) USING DELTA
  COMMENT 'Quarantine zone for records failing quality checks'
  PARTITIONED BY (source_table)
  TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
  );

-- ============================================================
-- 4. Create Quality Management Tables
-- ============================================================

-- Table for storing data quality rules
CREATE TABLE IF NOT EXISTS `streamflix-lakehouse`.init_schema.quality_rules (
  rule_id STRING COMMENT 'Unique rule identifier',
  table_name STRING COMMENT 'Target table for this rule',
  rule_type STRING COMMENT 'Type: NOT_NULL, RANGE, PATTERN, CUSTOM',
  column_name STRING COMMENT 'Column to validate',
  rule_definition STRING COMMENT 'SQL expression or constraint definition',
  severity STRING COMMENT 'ERROR, WARNING, INFO',
  is_active BOOLEAN COMMENT 'Whether rule is currently enforced',
  created_at TIMESTAMP COMMENT 'Rule creation timestamp',
  updated_at TIMESTAMP COMMENT 'Last modification timestamp'
) USING DELTA
  COMMENT 'Data quality rules configuration for validation framework';

-- ============================================================
-- 5. Create Pipeline Metadata Tables
-- ============================================================

-- Pipeline run tracking
CREATE TABLE IF NOT EXISTS `streamflix-lakehouse`.init_schema.pipeline_runs (
  run_id STRING COMMENT 'Unique run identifier (UUID)',
  pipeline_name STRING COMMENT 'Name of the pipeline/notebook',
  layer STRING COMMENT 'bronze, silver, or gold',
  start_time TIMESTAMP COMMENT 'Pipeline start timestamp',
  end_time TIMESTAMP COMMENT 'Pipeline end timestamp',
  status STRING COMMENT 'SUCCESS, FAILED, RUNNING',
  records_processed BIGINT COMMENT 'Total records processed',
  error_message STRING COMMENT 'Error details if failed',
  run_by STRING COMMENT 'User or service principal',
  cluster_id STRING COMMENT 'Cluster ID used for execution'
) USING DELTA
  COMMENT 'Pipeline execution history and monitoring'
  PARTITIONED BY (layer)
  TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true'
  );

-- ============================================================
-- 6. Create Volumes for File Storage
-- ============================================================
CREATE VOLUME IF NOT EXISTS `streamflix-lakehouse`.bronze.raw_data
  COMMENT 'External storage for raw data files before ingestion';

CREATE VOLUME IF NOT EXISTS `streamflix-lakehouse`.bronze.checkpoints
  COMMENT 'Auto Loader checkpoint storage for streaming ingestion';

CREATE VOLUME IF NOT EXISTS `streamflix-lakehouse`.silver.quarantine_files
  COMMENT 'Storage for quarantined data files';

-- ============================================================
-- 7. Insert Default Quality Rules (Optional)
-- ============================================================

-- Example quality rules for common validations
INSERT INTO `streamflix-lakehouse`.init_schema.quality_rules VALUES
  ('QR001', 'streamflix-lakehouse.bronze.*', 'NOT_NULL', '_metadata', '_metadata IS NOT NULL', 'ERROR', true, current_timestamp(), current_timestamp()),
  ('QR002', 'streamflix-lakehouse.silver.*', 'NOT_NULL', 'id', 'id IS NOT NULL', 'ERROR', true, current_timestamp(), current_timestamp()),
  ('QR003', 'streamflix-lakehouse.silver.*', 'RANGE', 'created_at', 'created_at >= ''2020-01-01''', 'WARNING', true, current_timestamp(), current_timestamp());

-- ============================================================
-- 8. Grant Permissions (Uncomment and adjust based on groups)
-- ============================================================

-- Data Engineers - Full access to all schemas
-- GRANT USAGE ON CATALOG `streamflix-lakehouse` TO `data-engineers`;
-- GRANT ALL PRIVILEGES ON SCHEMA `streamflix-lakehouse`.bronze TO `data-engineers`;
-- GRANT ALL PRIVILEGES ON SCHEMA `streamflix-lakehouse`.silver TO `data-engineers`;
-- GRANT ALL PRIVILEGES ON SCHEMA `streamflix-lakehouse`.gold TO `data-engineers`;
-- GRANT ALL PRIVILEGES ON SCHEMA `streamflix-lakehouse`.init_schema TO `data-engineers`;

-- BI Analysts - Read access to gold layer
-- GRANT USAGE ON CATALOG `streamflix-lakehouse` TO `bi-analysts`;
-- GRANT SELECT ON SCHEMA `streamflix-lakehouse`.gold TO `bi-analysts`;
-- GRANT SELECT ON TABLE `streamflix-lakehouse`.silver.audit_log TO `bi-analysts`;

-- Business Users - Read access to gold only
-- GRANT USAGE ON CATALOG `streamflix-lakehouse` TO `business-users`;
-- GRANT SELECT ON SCHEMA `streamflix-lakehouse`.gold TO `business-users`;

-- Data Scientists - Read silver/gold, write to gold
-- GRANT USAGE ON CATALOG `streamflix-lakehouse` TO `data-scientists`;
-- GRANT SELECT ON SCHEMA `streamflix-lakehouse`.silver TO `data-scientists`;
-- GRANT ALL PRIVILEGES ON SCHEMA `streamflix-lakehouse`.gold TO `data-scientists`;

-- ============================================================
-- 9. Verification Queries
-- ============================================================

-- Verify catalog
SELECT 'Catalog Verification' AS check_type,
       COUNT(*) AS schema_count
FROM system.information_schema.schemata
WHERE catalog_name = 'streamflix-lakehouse';

-- List all schemas
SHOW SCHEMAS IN `streamflix-lakehouse`;

-- List tables in each schema
SHOW TABLES IN `streamflix-lakehouse`.init_schema;
SHOW TABLES IN `streamflix-lakehouse`.silver;

-- List volumes
SHOW VOLUMES IN `streamflix-lakehouse`.bronze;
SHOW VOLUMES IN `streamflix-lakehouse`.silver;

-- Verify audit_log table structure
DESCRIBE EXTENDED `streamflix-lakehouse`.silver.audit_log;

-- Check quality rules inserted
SELECT * FROM `streamflix-lakehouse`.init_schema.quality_rules;

-- ============================================================
-- 10. Summary Report
-- ============================================================
SELECT
  'StreamFlix Lakehouse Initialization Complete' AS status,
  current_timestamp() AS completed_at,
  current_user() AS initialized_by;

-- End of initialization script
-- ============================================================
